ReactorKit/ReactorKit

Sources/Reactor.swift, Tests/ReactorKitTests/ReactorTests.swift
A state stream is a cold observable by default. So the states are not changed until the view subscribes the state stream. `autosubscribe()` changes the state stream behavior from cold observable to hot observable. This is useful when using reactors with reusable views.
=> Add autosubscribe feature

Sources/View.swift, Tests/ReactorKitTests/ViewTests.swift
ReactorKit was not well-considered for a storyboard. Assigning a reactor to a view makes `bind(reactor:)` get called. When using storyboard it occurs a runtime error about a force unwrapping of optionals. It's because the timing of the `bind(reactor:)` is prior to a storyboard initialization. This PR provides a better storyboard support by deferring a binding when a view is not yet loaded.
* Defer a `bind(reactor:)` execution until a view is loaded.
* Add tests for deferring binding.
* Update examples to assign reactors outside of view controllers.
* Please review `Sources/View.swift` which is the core change. Other files are about tests and examples.
* It only works for view controllers: UIViewController, NSViewController. Should I have to consider normal views(UIView, NSView)?
It can …
=> Defer bind() when a view is not yet loaded

Sources/ReactorKit/Reactor.swift, Tests/ReactorKitTests/ReactorTests.swift
I found something weird. Reactor's `action` is created again after the state stream is created when subclassing a generic class.
```swift
// Generic class
class ParentReactor<T>: Reactor {
enum Action {}
typealias Mutation = Void
typealias State = Void
let initialState: State = State()
}
// Subclass
class ChildReactor: ParentReactor<String> {
}
let reactor = ChildReactor()
let address1 = ObjectIdentifier(reactor.action).hashValue // 140212178080688
_ = reactor.state // will call createStateSteam()
let address2 = ObjectIdentifier(reactor.action).hashValue // 140212178094112
XCTAssertEqual(address1, address2) // FAIL
```
=> Bypass a Swift compiler bug in generic subclass associated object

.travis.yml
* [codecov-bash](https://github.com/codecov/codecov-bash) has changed its behavior from https://github.com/codecov/codecov-bash/commit/c90a47936d8de4db33047c1193a0bf649d00e363 so the coverage files are not being processed for a while.
* https://github.com/codecov/codecov-bash/pull/73
* Coverage report of this commits can be found at: https://codecov.io/gh/ReactorKit/ReactorKit/commit/7726f4dbbc74f8f26dc6cd3aa3487d6b588f13e3
=> Use codecov with '-X xcodeplist' option

Sources/ReactorKit/Reactor.swift, Tests/ReactorKitTests/ReactorTests.swift
If the state weren't subscribed from anywhere, actions sent to Reactor would be simply ignored.
```swift
func bind(reactor: Reactor) {
reactor.action.onNext(.load)
}
```
Touch `state` property in `action` property to ensure the initialization of the state stream
=> Create a state stream as the action property being accessed

Examples/Counter/Podfile, Examples/GitHubSearch/Podfile
`rxswift4.0` branch does not exist any more.
=> Fix error on pod install

README.md
I plan on helping out with your PR for SPM support for Carthage (https://github.com/Carthage/Carthage/pull/1945), but in the meantime I think it would reduce your support burden if users could more easily find out how to use ReactorKit with Carthage. In other words, this means fewer issues like #81 or #65
PS: My text editor ate some whitespace, but I hope you don't mind ;)
=> Add Carthage troubleshooting info to README

README.md, Sources/ReactorKit/StateRelay.swift, Sources/ReactorKit/Stub.swift, Tests/ReactorKitTests/StateRelayTests.swift
How about create `StateRelay` like `BehaviorRelay`?
If you want to use BehaviorRelay without `RxCocoa`, let me suggest you a create new `ObservableType`.
`StateRelay` consist of `BehaviorRelay` and `Variable` just :)
=> Use StateRelay instead of Variable

Tests/ReactorKitTests/ActionSubjectTests.swift, Tests/ReactorKitTests/ReactorTests.swift
See https://github.com/ReactiveX/RxSwift/pull/1510 and [RxSwift - 4.1.0](https://github.com/ReactiveX/RxSwift/releases/tag/4.1.0)
=> Fix next (global) to Recorded.next because of deprecated

Sources/ReactorKit/Reactor.swift, Tests/ReactorKitTests/ViewTests.swift
Since `Never` could not be instantiated, so I think using it will be better than `NoAction` and `NoMutation`.
=> Use Never instead of NoAction / NoMutation

README.md
Cathage seems to allow only `"` not `'` as a quote in the syntax.
And also, Carthage made by swift, that's why to change the syntax highlight for Carthage example.
https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Cartfile.swift#L190
=> Fix the parsing error for Carthage example.

Sources/ReactorKitRuntime/ReactorKitRuntime.m
Fix crash, because the SubViewController maybe inherit a BaseViewController, all the UI not initialization
=> 修复实现StoryboardView协议，提前bind导致的Crash

Sources/ReactorKit/Reactor+Equatable.swift, Sources/ReactorKit/Reactor+Hashable.swift, Tests/ReactorKitTests/ReactorEquatableTests.swift, Tests/ReactorKitTests/ReactorHashableTests.swift
If a Reactor has other Reactors as a State, it is difficult to use `distinctUntilChanged()` on it. It's important to use `distinctUntilChanged()` to prevent from unnecessary view re-rendering. This PR introduces a new functionality that automatically makes Reactor as an Equatable/Hashable if its State is also an Equatable/Hashable.
**Before**
```swift
class ItemListReactor {
struct State {
var itemReactors: [ItemReactor]
}
}
```
```swift
reactor.state.map { $0 }
.distinctUntilChanged() // 🚫 [ItemReactor] is not Equatable
.subscribe(...)
```
**After**
<pre>
class ItemListReactor<strong>: Equatable</strong> {
struct State<strong>: Equatable</strong> {
var itemReactors: [ItemReactor]
}
}
</pre>
```swift
reactor.state.map { $0 }
.distinctUntilChanged() // ✅
.subscribe(...)
```
=> Make Reactor Equatable and Hashable if State is Equatable or Hashable

README.md, Sources/ReactorKit/Reactor.swift, Tests/ReactorKitTests/ReactorSchedulerTests.swift
Define `scheduler` property to specify which scheduler is used for reducing and observing the state stream. Note that this queue **must be** a serial queue. The default scheduler is `CurrentThreadScheduler`.
```swift
final class MyReactor: Reactor {
let scheduler: Scheduler = SerialDispatchQueueScheduler(qos: .default)
func reduce(state: State, mutation: Mutation) -> State {
// executed in a background thread
heavyAndImportantCalculation()
return state
}
}
```
=> Add an availability to specify a scheduler

Sources/ReactorKit/Exports.swift
RxSwift is now automatically imported with `import ReactorKit`
=> Import RxSwift with @_exported attribute

Sources/ReactorKit/Reactor.swift, Tests/ReactorKitTests/ReactorSchedulerTests.swift, Tests/ReactorKitTests/ReactorTests.swift
If the `mutate()` and `reduce()` are performed in the difference scheduler, it will break the proper order of executions.
=> Ensure that mutate and reduce are executed in the same serial scheduler

Sources/ReactorKit/Reactor.swift, Tests/ReactorKitTests/ReactorSchedulerTests.swift
In the existing `Reactor` implementation code, The operation publishing the first state is executed by the scheduler assigned to the `Reactor`.
As a result, the first time you subscribed to the state stream, the first state isn't observed immediately at the same time you subscribed. This issue can lead to the problem that the required data isn't filled when the UI is first drawn.
This PR ensures that the last state, published to the state stream, can be observed as soon as you subscribe to the stream. In addition, it ensures consistency of when the last state was observed.
- The logic that handles the observed state can be executed immediately upon subscription.
- Executing the logic immediately means that the thread, calling the stream subscription, executes the logic immediately after …
=> Ensure that the last published state can be observed immediately.

Package.swift
While building ReactorKit with Carthage using XCode 12, the build fails with a bunch of error messages about iOS 8 being an unsupported deployment target.  Increasing the deployment target to iOS 9 in the Swift Package definition file resolves the issue.
```
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'RxSwift' from project 'ReactorKit')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'ReactorKitRuntime' from project 'ReactorKit')
** ARCHIVE FAILED **
The following build commands failed:
CompileSwift normal armv7
CompileSwiftSources normal arm64 …
```
=> Update Swift Package to be compatible with XCode 12

README.md
delete `isEnabled` from View testing description. Because, It's deprecated.
Also update  test cases example. replace `stub.isEnabled` to `isStubEnabled`.
=> Update View testing description

Package.resolved, Package.swift, ReactorKit.podspec, Sources/ReactorKit/Reactor.swift, Tests/ReactorKitTests/ReactorTests.swift
This PR has dependent of #171. If you don't want merge #171, I'll revert #171 on this PR.
=> Let's RxSwift 6.0 🚀

Sources/ReactorKit/IdentityEquatable.swift, Sources/ReactorKit/Reactor.swift, Sources/ReactorKit/View.swift
Fix deprecated class type to AnyObject type
`class` and `AnyObject` are parses identically.
`class` display some warnings because it is deprecated.
Ref: https://forums.swift.org/t/class-only-protocols-class-vs-anyobject/11507/10
```swift
public protocol IdentityEquatable: class, Equatable {
// ...
}
```
```swift
public protocol IdentityEquatable: AnyObject, Equatable {
// ...
}
```
=> Fix deprecated class type to AnyObject type

Sources/ReactorKitRuntime/ReactorKitRuntime.m
My app using ReactorKit got crashed when previewing SwiftUI with infinite call to +initialize:
By swizzle viewDidLoad in +load rather than +initialize, this issue can be solved. BTW, according to [NSHipster](https://nshipster.com/method-swizzling/#load-vs-initialize), swizzling in +initialize should be avoided.
=> Swizzle viewDidLoad in +load rather than +initialize.

.github/workflows/ci.yml
[Codecov bash uploader was deprecated](https://docs.codecov.com/docs/about-the-codecov-bash-uploader)
Accordingly, changed it to [Codecov Uploader](https://github.com/marketplace/actions/codecov). (fd85ca48e45be15214c803567a34208e82c2a8c0) 
Changes to xcode support for codecov-action v3 have also been added. (141a2f5d08dbf83bc0676bf3b9907ea4a73142c9)
Ref: https://docs.codecov.com/docs/codecov-uploader
=> Update deprecated bash uploader

Examples/Counter/Counter.xcodeproj/project.pbxproj, Examples/Podfile.lock
ReactorKit has been updated to 3.2.0, but the Podfile.lock in the Example project was not updated.
=> Update Example environment

Sources/ReactorKit/ActionSubject.swift
This pull request fixes the lock access modifier and changes var to let in the ActionSubject class.
The lock access modifier is changed to private to ensure thread safety and changed from var to let to prevent accidental modification.
The original lock access modifier was public, which means that any code could access the lock. This could lead to race conditions if multiple threads were accessing the lock at the same time.
also, lock property was var, which means that it could be modified by external code. This could lead to unexpected behavior if the value of lock was modified incorrectly.
By changing the lock access modifier to private and property to let, we can improve the thread safety and prevent accidental modification of the ActionSubject class
=> fix: lock access modifier and changed `var` to `let`

README.md, Sources/ReactorKit/Reactor.swift, Tests/ReactorKitTests/ReactorSchedulerTests.swift
When an action is sent to a reactor it is run on the current state and this process cannot be done from multiple threads
It is possible to make this process thread-safe by introducing scheduler, but this cause other problems
Those APIs tend to deliver their outputs on whatever thread is most convenient for them, and then it is your responsibility
ReactorKit makes you responsible for making sure to send actions on the main thread. If you may mutate states on a non-main thread, you must explicitly perform `.observe(on:)` in order to force it back on the main thread.
=> feat: remove scheduler in Reactor

Sources/ReactorKit/ActionSubject.swift, Sources/ReactorKit/Reactor+Pulse.swift, Tests/ReactorKitTests/StateRelayTests.swift
I remove Inline attribute commit from [here #221](https://github.com/ReactorKit/ReactorKit/pull/221#issue-1968352416)
- Update access modifier 
- Add comment for pulse operation
- Update Bool variable naming
=> Update access modifier, add comment, and update variable naming

Sources/ReactorKit/Pulse.swift
`Pulse` didn't have any documentation comments, even though it's a public interface. Also almost certainly need to refer to the documentation to know how to use it, so I added a summary with link to official document.
=> Add documentation comment

Sources/ReactorKit/Pulse.swift
- Changed the projectedValue return type from Pulse<Value> to Self
- Improves code flexibility and maintainability
=> Refactor projectedValue to use Self as the return type

Examples/Counter/Counter/CounterViewController.swift
The number was incremented or decremented multiple times with successive button clicks.
Added throttle to prevent continuous event emission during timer.
https://github.com/ReactorKit/ReactorKit/assets/91649269/276d5d53-b715-4dd2-a110-c634dfa520a2
=> Add: Adding throttle to the counter example

README.md
Scheduling items no longer exist, and clicking on them in the table of contents does not work
=> [Minor] Remove Unnecessary Scheduling Table of Contents from README.md

.github/workflows/ci.yml, Sources/ReactorKit/Reactor.swift
This PR cleans up unused and obsolete typealiases and improves CI stability in preparation for Swift 6:
- Removes the `Scheduler` typealias, which was defined but never used. This was likely missed in #218.
- Removes `NoAction` and `NoMutation` typealiases that were previously marked as `@available(*, obsoleted: 0, renamed: "Never")`. These were already unusable and now cause a compiler error in Swift 6.
- Updates the GitHub Actions CI script to dynamically select the latest available iOS Simulator. This avoids hardcoding device names and improves CI robustness.
These changes are safe to land and help clean up compatibility issues ahead of Swift 6 adoption.
=> Prepare for Swift 6: remove obsolete typealiases and update CI
